import selenium
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium import webdriver  
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities  
driver = webdriver.Edge()
url=" http://localhost:5173/"
driver.get(url)
driver.maximize_window()
time.sleep(2)
signup_bt=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/nav/div/div/button[2]")))
signup_bt.click()
time.sleep(3)
print("Signed button clicked")
signin_bt=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/nav/div/div/button[1]")))
signin_bt.click()
print("Signin button clicked")
time.sleep(3)
search_bar=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[1]/input")))
search_bar.send_keys("testing")
print("Search bar clicked")
print("search success")
driver.refresh()
time.sleep(8)
filter_bt=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[1]")))
filter_bt.click()
print("Filter button clicked")
time.sleep(4)
recent_fliter=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[1]/option[2]")))
recent_fliter.click()
print("Recent filter clicked")
time.sleep(4)
pouplar_fliter=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[1]/option[3]")))
pouplar_fliter.click()
print("Pouplar filter clicked")
time.sleep(4)
driver.refresh()
time.sleep(4)
short_fliter=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[2]/option[2]")))
short_fliter.click()
print("Short filter clicked")
time.sleep(4)
sortby_date=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[2]/option[2]")))
sortby_date.click()
print("Sort by date clicked")
sortby_title=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[2]/option[1]")))
sortby_title.click()
print("Sort by title clicked")
time.sleep(4)
sortby_rating=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[1]/div[2]/select[2]/option[3]   ")))
sortby_rating.click()
print("Sort by rating clicked")
time.sleep(4)
driver.refresh()
time.sleep(2)
action=ActionChains(driver)
video= driver.find_element(By.XPATH,"//*[@id='root']/div/main/div/div[2]/div[1]/img")
action.move_to_element(video).perform()
print("Video hovered")
time.sleep(4)
click_video= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[2]/div[1]/img")))
click_video.click()
print("Video clicked")
time.sleep(4)
play_bt= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/button[1]")))
play_bt.click()
print("Play button clicked")
time.sleep(4)
mute_bt= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/div[2]/button")))
mute_bt.click()
print("Mute button clicked")
time.sleep(4)
playbackspeed= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/div[3]/select")))
playbackspeed.click()
print("Playback speed clicked")
time.sleep(4)
select_speed= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/div[3]/select/option[1]")))
select_speed.click()
print("Speed selected")
time.sleep(4)
bookmark_bt= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/button[2]")))
bookmark_bt.click()
print("Bookmark button clicked")
time.sleep(4)
autoplay_enable= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/div[4]/label[1]/input")))
autoplay_enable.click()
print("Autoplay enabled")
time.sleep(4)
subtitle_enable= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[1]/div[2]/div[4]/label[2]/input")))
subtitle_enable.click()
print("Subtitle enabled")
time.sleep(4)
type_command= driver.find_element(By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[2]/div[1]/div/form/textarea")
type_command.send_keys("Best video ever seen")
time.sleep(2)
print("Command typed")
time.sleep(4)
post_command= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[2]/div[1]/div/form/button")))
post_command.click()
print("Command posted")
time.sleep(4)

fire_button= WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[2]/div[1]/div/div/div/div[1]/button")))
fire_button.click()
print("Fire button clicked")
time.sleep(4)
commentreplay=driver.find_element(By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[2]/div[1]/div/div/div/div[2]/form/input")
commentreplay.send_keys("Yes bro")
time.sleep(2)
print("Comment replayed")
clickreplay=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,"//*[@id='root']/div/main/div/div[3]/div[2]/div[1]/div/div/div/div[2]/form/button")))
clickreplay.click()
print("Comment replayed")
time.sleep(4)
driver.quit()